# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cookGUI(object):
    def setupUi(self, cookGUI):
        cookGUI.setObjectName("cookGUI")
        cookGUI.resize(1081, 825)
        cookGUI.setStyleSheet("QMainWindow#cookGUI{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(cookGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.orderSlot1 = QtWidgets.QWidget(self.centralwidget)
        self.orderSlot1.setStyleSheet("QWidget#orderSlot1{\n"
"border: 2px solid;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        self.orderSlot1.setObjectName("orderSlot1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.orderSlot1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.orderArea1 = QtWidgets.QWidget(self.orderSlot1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderArea1.sizePolicy().hasHeightForWidth())
        self.orderArea1.setSizePolicy(sizePolicy)
        self.orderArea1.setStyleSheet("border-bottom: 2px solid green;")
        self.orderArea1.setObjectName("orderArea1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.orderArea1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.orderArea1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 170, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.orderArea1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.orderNum1 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderNum1.sizePolicy().hasHeightForWidth())
        self.orderNum1.setSizePolicy(sizePolicy)
        self.orderNum1.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 170, 0);")
        self.orderNum1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.orderNum1.setObjectName("orderNum1")
        self.horizontalLayout_3.addWidget(self.orderNum1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.orderArea1)
        self.widget_5 = QtWidgets.QWidget(self.orderSlot1)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.widget_5)
        self.listWidget.setStyleSheet("font: 12pt \"Arial\";\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.doneButton1 = QtWidgets.QPushButton(self.widget_5)
        self.doneButton1.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.doneButton1.setObjectName("doneButton1")
        self.verticalLayout_2.addWidget(self.doneButton1)
        self.verticalLayout.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.orderSlot1)
        self.orderSlot2 = QtWidgets.QWidget(self.centralwidget)
        self.orderSlot2.setStyleSheet("QWidget#orderSlot2{\n"
"border: 2px solid;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        self.orderSlot2.setObjectName("orderSlot2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.orderSlot2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.orderArea2 = QtWidgets.QWidget(self.orderSlot2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderArea2.sizePolicy().hasHeightForWidth())
        self.orderArea2.setSizePolicy(sizePolicy)
        self.orderArea2.setStyleSheet("border-bottom: 2px solid green;")
        self.orderArea2.setObjectName("orderArea2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.orderArea2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.orderArea2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 170, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.orderArea2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.orderNum2 = QtWidgets.QLabel(self.frame_4)
        self.orderNum2.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 170, 0);")
        self.orderNum2.setObjectName("orderNum2")
        self.horizontalLayout_7.addWidget(self.orderNum2)
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.verticalLayout_6.addWidget(self.orderArea2)
        self.widget_9 = QtWidgets.QWidget(self.orderSlot2)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.widget_9)
        self.listWidget_2.setStyleSheet("font: 12pt \"Arial\";\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.listWidget_2)
        self.doneButton2 = QtWidgets.QPushButton(self.widget_9)
        self.doneButton2.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 20pt \"Arial\";")
        self.doneButton2.setObjectName("doneButton2")
        self.verticalLayout_3.addWidget(self.doneButton2)
        self.verticalLayout_6.addWidget(self.widget_9)
        self.horizontalLayout.addWidget(self.orderSlot2)
        self.orderSlot3 = QtWidgets.QWidget(self.centralwidget)
        self.orderSlot3.setStyleSheet("QWidget#orderSlot3{\n"
"border: 2px solid;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        self.orderSlot3.setObjectName("orderSlot3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.orderSlot3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.orderArea3 = QtWidgets.QWidget(self.orderSlot3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderArea3.sizePolicy().hasHeightForWidth())
        self.orderArea3.setSizePolicy(sizePolicy)
        self.orderArea3.setStyleSheet("border-bottom: 2px solid green;")
        self.orderArea3.setObjectName("orderArea3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.orderArea3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.orderArea3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 170, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.horizontalLayout_8.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.orderArea3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.orderNum3 = QtWidgets.QLabel(self.frame_6)
        self.orderNum3.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 170, 0);")
        self.orderNum3.setObjectName("orderNum3")
        self.horizontalLayout_10.addWidget(self.orderNum3)
        self.horizontalLayout_8.addWidget(self.frame_6)
        self.verticalLayout_7.addWidget(self.orderArea3)
        self.widget_10 = QtWidgets.QWidget(self.orderSlot3)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.widget_10)
        self.listWidget_3.setStyleSheet("font: 12pt \"Arial\";\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_4.addWidget(self.listWidget_3)
        self.doneButton3 = QtWidgets.QPushButton(self.widget_10)
        self.doneButton3.setStyleSheet("color: rgb(0, 170, 0);\n"
"font:20pt \"Arial\";")
        self.doneButton3.setObjectName("doneButton3")
        self.verticalLayout_4.addWidget(self.doneButton3)
        self.verticalLayout_7.addWidget(self.widget_10)
        self.horizontalLayout.addWidget(self.orderSlot3)
        self.orderSlot4 = QtWidgets.QWidget(self.centralwidget)
        self.orderSlot4.setStyleSheet("QWidget#orderSlot4{\n"
"border: 2px solid;\n"
"border-color: rgb(0, 170, 0);\n"
"}")
        self.orderSlot4.setObjectName("orderSlot4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.orderSlot4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.orderArea4 = QtWidgets.QWidget(self.orderSlot4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderArea4.sizePolicy().hasHeightForWidth())
        self.orderArea4.setSizePolicy(sizePolicy)
        self.orderArea4.setStyleSheet("border-bottom: 2px solid green;")
        self.orderArea4.setObjectName("orderArea4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.orderArea4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_7 = QtWidgets.QFrame(self.orderArea4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 170, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.horizontalLayout_11.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.orderArea4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.orderNum4 = QtWidgets.QLabel(self.frame_8)
        self.orderNum4.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(0, 170, 0);")
        self.orderNum4.setObjectName("orderNum4")
        self.horizontalLayout_13.addWidget(self.orderNum4)
        self.horizontalLayout_11.addWidget(self.frame_8)
        self.verticalLayout_8.addWidget(self.orderArea4)
        self.widget_11 = QtWidgets.QWidget(self.orderSlot4)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget_4 = QtWidgets.QListWidget(self.widget_11)
        self.listWidget_4.setStyleSheet("font: 12pt \"Arial\";\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.listWidget_4.setObjectName("listWidget_4")
        self.verticalLayout_5.addWidget(self.listWidget_4)
        self.doneButton4 = QtWidgets.QPushButton(self.widget_11)
        self.doneButton4.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 20pt \"Arial\";")
        self.doneButton4.setObjectName("doneButton4")
        self.verticalLayout_5.addWidget(self.doneButton4)
        self.verticalLayout_8.addWidget(self.widget_11)
        self.horizontalLayout.addWidget(self.orderSlot4)
        cookGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(cookGUI)
        QtCore.QMetaObject.connectSlotsByName(cookGUI)

    def retranslateUi(self, cookGUI):
        _translate = QtCore.QCoreApplication.translate
        cookGUI.setWindowTitle(_translate("cookGUI", "MainWindow"))
        self.label.setText(_translate("cookGUI", "Order: "))
        self.orderNum1.setText(_translate("cookGUI", "00"))
        self.doneButton1.setText(_translate("cookGUI", "DONE"))
        self.label_4.setText(_translate("cookGUI", "Order: "))
        self.orderNum2.setText(_translate("cookGUI", "00"))
        self.doneButton2.setText(_translate("cookGUI", "DONE"))
        self.label_6.setText(_translate("cookGUI", "Order: "))
        self.orderNum3.setText(_translate("cookGUI", "00"))
        self.doneButton3.setText(_translate("cookGUI", "DONE"))
        self.label_8.setText(_translate("cookGUI", "Order: "))
        self.orderNum4.setText(_translate("cookGUI", "00"))
        self.doneButton4.setText(_translate("cookGUI", "DONE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cookGUI = QtWidgets.QMainWindow()
    ui = Ui_cookGUI()
    ui.setupUi(cookGUI)
    cookGUI.show()
    sys.exit(app.exec_())
