# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finishOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_finishOrder(object):
    def setupUi(self, finishOrder):
        finishOrder.setObjectName("finishOrder")
        finishOrder.resize(1600, 900)
        finishOrder.setStyleSheet("QMainWindow#finishOrder{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.449, x2:0, y2:1, stop:0.60199 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(finishOrder)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topside = QtWidgets.QWidget(self.centralwidget)
        self.topside.setObjectName("topside")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topside)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftWidget = QtWidgets.QWidget(self.topside)
        self.leftWidget.setStyleSheet("QWidget#leftWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"}")
        self.leftWidget.setObjectName("leftWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orderHead = QtWidgets.QWidget(self.leftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderHead.sizePolicy().hasHeightForWidth())
        self.orderHead.setSizePolicy(sizePolicy)
        self.orderHead.setStyleSheet("border-bottom: 2px solid black;")
        self.orderHead.setObjectName("orderHead")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.orderHead)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.orderlbFrm = QtWidgets.QFrame(self.orderHead)
        self.orderlbFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.orderlbFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.orderlbFrm.setObjectName("orderlbFrm")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.orderlbFrm)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.orderLabel = QtWidgets.QLabel(self.orderlbFrm)
        self.orderLabel.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);\n"
"font: 26pt \"Arial\";")
        self.orderLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.orderLabel.setObjectName("orderLabel")
        self.horizontalLayout_5.addWidget(self.orderLabel)
        self.horizontalLayout_3.addWidget(self.orderlbFrm)
        self.ordernumfrm = QtWidgets.QFrame(self.orderHead)
        self.ordernumfrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ordernumfrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ordernumfrm.setObjectName("ordernumfrm")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ordernumfrm)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.orderNumLabel = QtWidgets.QLabel(self.ordernumfrm)
        self.orderNumLabel.setStyleSheet("border: none;\n"
"color: rgb(0, 0, 0);\n"
"font: 26pt \"Arial\";")
        self.orderNumLabel.setObjectName("orderNumLabel")
        self.horizontalLayout_4.addWidget(self.orderNumLabel)
        self.horizontalLayout_3.addWidget(self.ordernumfrm)
        self.verticalLayout_2.addWidget(self.orderHead)
        self.orderLstWid = QtWidgets.QWidget(self.leftWidget)
        self.orderLstWid.setObjectName("orderLstWid")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.orderLstWid)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.orderTableWidget = QtWidgets.QTableWidget(self.orderLstWid)
        self.orderTableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: rgb(213, 248, 255);\n"
"    padding: 2px;\n"
"    border: 1px solid;\n"
"\n"
"    font: 18pt \"Arial\";\n"
"}")
        self.orderTableWidget.setObjectName("orderTableWidget")
        self.orderTableWidget.setColumnCount(4)
        self.orderTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_6.addWidget(self.orderTableWidget)
        self.verticalLayout_2.addWidget(self.orderLstWid)
        self.horizontalLayout_2.addWidget(self.leftWidget)
        self.rightWidget = QtWidgets.QWidget(self.topside)
        self.rightWidget.setObjectName("rightWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.rightWidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.nameFrm = QtWidgets.QFrame(self.rightWidget)
        self.nameFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nameFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nameFrm.setObjectName("nameFrm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.nameFrm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nameLabel = QtWidgets.QLabel(self.nameFrm)
        self.nameLabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 26pt \"Forte\";")
        self.nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_3.addWidget(self.nameLabel)
        self.totalLabel = QtWidgets.QLabel(self.nameFrm)
        self.totalLabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 26pt \"Forte\";")
        self.totalLabel.setObjectName("totalLabel")
        self.verticalLayout_3.addWidget(self.totalLabel, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_7.addWidget(self.nameFrm)
        self.frame = QtWidgets.QFrame(self.rightWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.inputNameFrm = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputNameFrm.sizePolicy().hasHeightForWidth())
        self.inputNameFrm.setSizePolicy(sizePolicy)
        self.inputNameFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputNameFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputNameFrm.setObjectName("inputNameFrm")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.inputNameFrm)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.inputNameLineEdit = QtWidgets.QLineEdit(self.inputNameFrm)
        self.inputNameLineEdit.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 26pt \"Arial\";")
        self.inputNameLineEdit.setObjectName("inputNameLineEdit")
        self.verticalLayout_5.addWidget(self.inputNameLineEdit)
        self.verticalLayout_4.addWidget(self.inputNameFrm, 0, QtCore.Qt.AlignTop)
        self.inputTotalFrm = QtWidgets.QFrame(self.frame)
        self.inputTotalFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputTotalFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputTotalFrm.setObjectName("inputTotalFrm")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.inputTotalFrm)
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.displayTotal = QtWidgets.QLabel(self.inputTotalFrm)
        self.displayTotal.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 26pt \"Arial\";")
        self.displayTotal.setText("")
        self.displayTotal.setObjectName("displayTotal")
        self.horizontalLayout_8.addWidget(self.displayTotal, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_4.addWidget(self.inputTotalFrm)
        self.horizontalLayout_7.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.rightWidget)
        self.verticalLayout.addWidget(self.topside)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backBtn = QtWidgets.QPushButton(self.widget_2)
        self.backBtn.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(111, 210, 255);\n"
"font: 75 26pt \"Arial\";\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(21, 76, 152);")
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        spacerItem = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.submitOrderBtn = QtWidgets.QPushButton(self.widget_2)
        self.submitOrderBtn.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(111, 210, 255);\n"
"font: 75 26pt \"Arial\";\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(21, 76, 152);")
        self.submitOrderBtn.setObjectName("submitOrderBtn")
        self.horizontalLayout.addWidget(self.submitOrderBtn)
        self.verticalLayout.addWidget(self.widget_2)
        finishOrder.setCentralWidget(self.centralwidget)

        self.retranslateUi(finishOrder)
        QtCore.QMetaObject.connectSlotsByName(finishOrder)

    def retranslateUi(self, finishOrder):
        _translate = QtCore.QCoreApplication.translate
        finishOrder.setWindowTitle(_translate("finishOrder", "MainWindow"))
        self.orderLabel.setText(_translate("finishOrder", "Order: "))
        self.orderNumLabel.setText(_translate("finishOrder", "00"))
        item = self.orderTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("finishOrder", "Menu Item "))
        item = self.orderTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("finishOrder", "Quantity"))
        item = self.orderTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("finishOrder", "Notes"))
        item = self.orderTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("finishOrder", "Price"))
        self.nameLabel.setText(_translate("finishOrder", "Name:"))
        self.totalLabel.setText(_translate("finishOrder", "Total:"))
        self.backBtn.setText(_translate("finishOrder", "Back"))
        self.submitOrderBtn.setText(_translate("finishOrder", "Submit Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    finishOrder = QtWidgets.QMainWindow()
    ui = Ui_finishOrder()
    ui.setupUi(finishOrder)
    finishOrder.show()
    sys.exit(app.exec_())
