# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manageOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 333)
        MainWindow.setStyleSheet("background-color: rgb(89, 89, 89);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ordersLabel = QtWidgets.QLabel(self.widget)
        self.ordersLabel.setStyleSheet("font: 28pt \"Courier New\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"border-color: rgb(0, 255, 0);\n"
"border-style: outset;\n"
"border-width: 2px;")
        self.ordersLabel.setObjectName("ordersLabel")
        self.verticalLayout_2.addWidget(self.ordersLabel)
        self.ordersList = QtWidgets.QListWidget(self.widget)
        self.ordersList.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"font: 36pt \"Courier New\";\n"
"color: rgb(0, 255, 0);\n"
"border-color: rgb(0, 255, 0);\n"
"selection-background-color: rgb(255, 0, 0);\n"
"border-style: outset;\n"
"border-width: 3px;")
        self.ordersList.setObjectName("ordersList")
        self.verticalLayout_2.addWidget(self.ordersList)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(600, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.backButton = QtWidgets.QPushButton(self.widget_2)
        self.backButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 255, 0);\n"
"font: 28pt \"Courier New\";")
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        spacerItem1 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.manageButton = QtWidgets.QPushButton(self.widget_2)
        self.manageButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 255, 0);\n"
"font: 28pt \"Courier New\";")
        self.manageButton.setObjectName("manageButton")
        self.horizontalLayout.addWidget(self.manageButton)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ordersLabel.setText(_translate("MainWindow", "ORDERS"))
        self.backButton.setText(_translate("MainWindow", "GO BACK"))
        self.manageButton.setText(_translate("MainWindow", "MANAGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
