# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcomeScreen(object):
    def setupUi(self, welcomeScreen):
        welcomeScreen.setObjectName("welcomeScreen")
        welcomeScreen.resize(1600, 900)
        welcomeScreen.setStyleSheet("QMainWindow#welcomeScreen{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.449, x2:0, y2:1, stop:0.60199 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(welcomeScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topWidget.sizePolicy().hasHeightForWidth())
        self.topWidget.setSizePolicy(sizePolicy)
        self.topWidget.setObjectName("topWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.welcomeLabel = QtWidgets.QLabel(self.topWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomeLabel.sizePolicy().hasHeightForWidth())
        self.welcomeLabel.setSizePolicy(sizePolicy)
        self.welcomeLabel.setStyleSheet("color: rgb(255, 1, 1);\n"
"font: 86pt \"Gabriola\";")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.horizontalLayout_2.addWidget(self.welcomeLabel)
        self.verticalLayout.addWidget(self.topWidget)
        self.middleWidget = QtWidgets.QWidget(self.centralwidget)
        self.middleWidget.setObjectName("middleWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.middleWidget)
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 95)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logoLabel = QtWidgets.QLabel(self.middleWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logoLabel.setStyleSheet("image: url(:/logo/Los_Pollos.webp);")
        self.logoLabel.setText("")
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_3.addWidget(self.logoLabel)
        self.verticalLayout.addWidget(self.middleWidget)
        self.buttomWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttomWidget.sizePolicy().hasHeightForWidth())
        self.buttomWidget.setSizePolicy(sizePolicy)
        self.buttomWidget.setObjectName("buttomWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttomWidget)
        self.horizontalLayout.setContentsMargins(11, -1, -1, 25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.manageOrderBtn = QtWidgets.QPushButton(self.buttomWidget)
        self.manageOrderBtn.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(111, 210, 255);\n"
"font: 75 26pt \"Arial\";\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(21, 76, 152);\n"
"")
        self.manageOrderBtn.setObjectName("manageOrderBtn")
        self.horizontalLayout.addWidget(self.manageOrderBtn)
        spacerItem1 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.createOrderBtn = QtWidgets.QPushButton(self.buttomWidget)
        self.createOrderBtn.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(111, 210, 255);\n"
"font: 75 26pt \"Arial\";\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(21, 76, 152);")
        self.createOrderBtn.setObjectName("createOrderBtn")
        self.horizontalLayout.addWidget(self.createOrderBtn)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.buttomWidget)
        welcomeScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(welcomeScreen)
        QtCore.QMetaObject.connectSlotsByName(welcomeScreen)

    def retranslateUi(self, welcomeScreen):
        _translate = QtCore.QCoreApplication.translate
        welcomeScreen.setWindowTitle(_translate("welcomeScreen", "MainWindow"))
        self.welcomeLabel.setText(_translate("welcomeScreen", "Welcome"))
        self.manageOrderBtn.setText(_translate("welcomeScreen", "Manage Order"))
        self.createOrderBtn.setText(_translate("welcomeScreen", "Create Order"))
import logosource


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    welcomeScreen = QtWidgets.QMainWindow()
    ui = Ui_welcomeScreen()
    ui.setupUi(welcomeScreen)
    welcomeScreen.show()
    sys.exit(app.exec_())
